In [12]:
from pprint import pprint
import pandas as pd
import seaborn as sns
import pymongo
client = pymongo.MongoClient("mongodb+srv://yashmohite:12345678ym@cluster0.urvqe3y.mongodb.net/?retryWrites=true&w=majority")
db = client.test #pointer 
print(db)

Database(MongoClient(host=['ac-d6qyvfk-shard-00-02.urvqe3y.mongodb.net:27017', 'ac-d6qyvfk-shard-00-01.urvqe3y.mongodb.net:27017', 'ac-d6qyvfk-shard-00-00.urvqe3y.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', authsource='admin', replicaset='atlas-lkhn33-shard-0', tls=True), 'test')

In [6]:
data = sns.load_dataset("titanic")

In [7]:
db = client["titanic"]

In [8]:
collection = db["record"]

In [10]:
data = data.to_dict(orient="record")

C:\Users\yash mohite\AppData\Local\Temp\ipykernel_13244\2704615251.py:1: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  data = data.to_dict(orient="record")

In [11]:
collection.insert_many(data)

In [15]:
for i in collection.find():
    pprint(i)

{'_id': ObjectId('63e7ada1fe31db2740c6a28c'),
 'adult_male': True,
 'age': 22.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 7.25,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 1,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a28d'),
 'adult_male': False,
 'age': 38.0,
 'alive': 'yes',
 'alone': False,
 'class': 'First',
 'deck': 'C',
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 71.2833,
 'parch': 0,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a28e'),
 'adult_male': False,
 'age': 26.0,
 'alive': 'yes',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 7.925,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a28f'),
 'adult_male': False,
 'age': 35.0,
 'alive': 'yes',
 'alone': False,
 'class': 'First',
 'deck': 'C',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 53.1,
 'parch': 0,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a290'),
 'adult_male': True,
 'age': 35.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 8.05,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a291'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 8.4583,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a292'),
 'adult_male': True,
 'age': 54.0,
 'alive': 'no',
 'alone': True,
 'class': 'First',
 'deck': 'E',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 51.8625,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a293'),
 'adult_male': False,
 'age': 2.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 21.075,
 'parch': 1,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 3,
 'survived': 0,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a294'),
 'adult_male': False,
 'age': 27.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 11.1333,
 'parch': 2,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a295'),
 'adult_male': False,
 'age': 14.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 30.0708,
 'parch': 0,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a296'),
 'adult_male': False,
 'age': 4.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Third',
 'deck': 'G',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 16.7,
 'parch': 1,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a297'),
 'adult_male': False,
 'age': 58.0,
 'alive': 'yes',
 'alone': True,
 'class': 'First',
 'deck': 'C',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.55,
 'parch': 0,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a298'),
 'adult_male': True,
 'age': 20.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 8.05,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a299'),
 'adult_male': True,
 'age': 39.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 31.275,
 'parch': 5,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 1,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a29a'),
 'adult_male': False,
 'age': 14.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 7.8542,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 0,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a29b'),
 'adult_male': False,
 'age': 55.0,
 'alive': 'yes',
 'alone': True,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 16.0,
 'parch': 0,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a29c'),
 'adult_male': False,
 'age': 2.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 29.125,
 'parch': 1,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 4,
 'survived': 0,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a29d'),
 'adult_male': True,
 'age': nan,
 'alive': 'yes',
 'alone': True,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 13.0,
 'parch': 0,
 'pclass': 2,
 'sex': 'male',
 'sibsp': 0,
 'survived': 1,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a29e'),
 'adult_male': False,
 'age': 31.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 18.0,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 1,
 'survived': 0,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a29f'),
 'adult_male': False,
 'age': nan,
 'alive': 'yes',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 7.225,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2a0'),
 'adult_male': True,
 'age': 35.0,
 'alive': 'no',
 'alone': True,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.0,
 'parch': 0,
 'pclass': 2,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2a1'),
 'adult_male': True,
 'age': 34.0,
 'alive': 'yes',
 'alone': True,
 'class': 'Second',
 'deck': 'D',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 13.0,
 'parch': 0,
 'pclass': 2,
 'sex': 'male',
 'sibsp': 0,
 'survived': 1,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2a2'),
 'adult_male': False,
 'age': 15.0,
 'alive': 'yes',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 8.0292,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2a3'),
 'adult_male': True,
 'age': 28.0,
 'alive': 'yes',
 'alone': True,
 'class': 'First',
 'deck': 'A',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 35.5,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 1,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2a4'),
 'adult_male': False,
 'age': 8.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 21.075,
 'parch': 1,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 3,
 'survived': 0,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2a5'),
 'adult_male': False,
 'age': 38.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 31.3875,
 'parch': 5,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2a6'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 7.225,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2a7'),
 'adult_male': True,
 'age': 19.0,
 'alive': 'no',
 'alone': False,
 'class': 'First',
 'deck': 'C',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 263.0,
 'parch': 2,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 3,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2a8'),
 'adult_male': False,
 'age': nan,
 'alive': 'yes',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 7.8792,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2a9'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 7.8958,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2aa'),
 'adult_male': True,
 'age': 40.0,
 'alive': 'no',
 'alone': True,
 'class': 'First',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 27.7208,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2ab'),
 'adult_male': False,
 'age': nan,
 'alive': 'yes',
 'alone': False,
 'class': 'First',
 'deck': 'B',
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 146.5208,
 'parch': 0,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2ac'),
 'adult_male': False,
 'age': nan,
 'alive': 'yes',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 7.75,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2ad'),
 'adult_male': True,
 'age': 66.0,
 'alive': 'no',
 'alone': True,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 10.5,
 'parch': 0,
 'pclass': 2,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2ae'),
 'adult_male': True,
 'age': 28.0,
 'alive': 'no',
 'alone': False,
 'class': 'First',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 82.1708,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 1,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2af'),
 'adult_male': True,
 'age': 42.0,
 'alive': 'no',
 'alone': False,
 'class': 'First',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 52.0,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 1,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2b0'),
 'adult_male': True,
 'age': nan,
 'alive': 'yes',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 7.2292,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 1,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2b1'),
 'adult_male': True,
 'age': 21.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 8.05,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2b2'),
 'adult_male': False,
 'age': 18.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 18.0,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 2,
 'survived': 0,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2b3'),
 'adult_male': False,
 'age': 14.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 11.2417,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2b4'),
 'adult_male': False,
 'age': 40.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 9.475,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 1,
 'survived': 0,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2b5'),
 'adult_male': False,
 'age': 27.0,
 'alive': 'no',
 'alone': False,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 21.0,
 'parch': 0,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 1,
 'survived': 0,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2b6'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 7.8958,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2b7'),
 'adult_male': False,
 'age': 3.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 41.5792,
 'parch': 2,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2b8'),
 'adult_male': False,
 'age': 19.0,
 'alive': 'yes',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 7.8792,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2b9'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 8.05,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2ba'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 15.5,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 1,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2bb'),
 'adult_male': False,
 'age': nan,
 'alive': 'yes',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 7.75,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2bc'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 21.6792,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 2,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2bd'),
 'adult_male': False,
 'age': 18.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 17.8,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 1,
 'survived': 0,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2be'),
 'adult_male': False,
 'age': 7.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 39.6875,
 'parch': 1,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 4,
 'survived': 0,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2bf'),
 'adult_male': True,
 'age': 21.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 7.8,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2c0'),
 'adult_male': False,
 'age': 49.0,
 'alive': 'yes',
 'alone': False,
 'class': 'First',
 'deck': 'D',
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 76.7292,
 'parch': 0,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2c1'),
 'adult_male': False,
 'age': 29.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.0,
 'parch': 0,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2c2'),
 'adult_male': True,
 'age': 65.0,
 'alive': 'no',
 'alone': False,
 'class': 'First',
 'deck': 'B',
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 61.9792,
 'parch': 1,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2c3'),
 'adult_male': True,
 'age': nan,
 'alive': 'yes',
 'alone': True,
 'class': 'First',
 'deck': 'C',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 35.5,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 1,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2c4'),
 'adult_male': False,
 'age': 21.0,
 'alive': 'yes',
 'alone': True,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 10.5,
 'parch': 0,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2c5'),
 'adult_male': True,
 'age': 28.5,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 7.2292,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2c6'),
 'adult_male': False,
 'age': 5.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 27.75,
 'parch': 2,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2c7'),
 'adult_male': False,
 'age': 11.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 46.9,
 'parch': 2,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 5,
 'survived': 0,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2c8'),
 'adult_male': True,
 'age': 22.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 7.2292,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2c9'),
 'adult_male': False,
 'age': 38.0,
 'alive': 'yes',
 'alone': True,
 'class': 'First',
 'deck': 'B',
 'embark_town': nan,
 'embarked': nan,
 'fare': 80.0,
 'parch': 0,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2ca'),
 'adult_male': True,
 'age': 45.0,
 'alive': 'no',
 'alone': False,
 'class': 'First',
 'deck': 'C',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 83.475,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 1,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2cb'),
 'adult_male': False,
 'age': 4.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 27.9,
 'parch': 2,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 3,
 'survived': 0,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2cc'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'First',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 27.7208,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2cd'),
 'adult_male': True,
 'age': nan,
 'alive': 'yes',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 15.2458,
 'parch': 1,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 1,
 'survived': 1,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a2ce'),
 'adult_male': False,
 'age': 29.0,
 'alive': 'yes',
 'alone': True,
 'class': 'Second',
 'deck': 'F',

 'alive': 'no',
 'alone': True,
 'class': 'First',
 'deck': 'B',
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 29.7,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a474'),
 'adult_male': True,
 'age': 30.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 8.05,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a475'),
 'adult_male': False,
 'age': 9.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 15.9,
 'parch': 1,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 1,
 'survived': 1,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a476'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 19.9667,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 1,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a477'),
 'adult_male': True,
 'age': 21.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 7.25,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a478'),
 'adult_male': True,
 'age': 55.0,
 'alive': 'no',
 'alone': True,
 'class': 'First',
 'deck': 'C',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 30.5,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a479'),
 'adult_male': True,
 'age': 71.0,
 'alive': 'no',
 'alone': True,
 'class': 'First',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 49.5042,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a47a'),
 'adult_male': True,
 'age': 21.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 8.05,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a47b'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 14.4583,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a47c'),
 'adult_male': False,
 'age': 54.0,
 'alive': 'yes',
 'alone': False,
 'class': 'First',
 'deck': 'D',
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 78.2667,
 'parch': 0,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a47d'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 15.1,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a47e'),
 'adult_male': False,
 'age': 25.0,
 'alive': 'no',
 'alone': False,
 'class': 'First',
 'deck': 'C',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 151.55,
 'parch': 2,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 1,
 'survived': 0,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a47f'),
 'adult_male': True,
 'age': 24.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 7.7958,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a480'),
 'adult_male': True,
 'age': 17.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 8.6625,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a481'),
 'adult_male': False,
 'age': 21.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 7.75,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 0,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a482'),
 'adult_male': False,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 7.6292,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 0,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a483'),
 'adult_male': False,
 'age': 37.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 9.5875,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 0,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a484'),
 'adult_male': False,
 'age': 16.0,
 'alive': 'yes',
 'alone': True,
 'class': 'First',
 'deck': 'B',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 86.5,
 'parch': 0,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a485'),
 'adult_male': True,
 'age': 18.0,
 'alive': 'no',
 'alone': False,
 'class': 'First',
 'deck': 'C',
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 108.9,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 1,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a486'),
 'adult_male': False,
 'age': 33.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.0,
 'parch': 2,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a487'),
 'adult_male': True,
 'age': nan,
 'alive': 'yes',
 'alone': True,
 'class': 'First',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.55,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 1,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a488'),
 'adult_male': True,
 'age': 28.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 22.525,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a489'),
 'adult_male': True,
 'age': 26.0,
 'alive': 'yes',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 56.4958,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 1,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a48a'),
 'adult_male': True,
 'age': 29.0,
 'alive': 'yes',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 7.75,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 1,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a48b'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 8.05,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a48c'),
 'adult_male': True,
 'age': 36.0,
 'alive': 'yes',
 'alone': True,
 'class': 'First',
 'deck': 'E',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.2875,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 1,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a48d'),
 'adult_male': False,
 'age': 54.0,
 'alive': 'yes',
 'alone': False,
 'class': 'First',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 59.4,
 'parch': 0,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a48e'),
 'adult_male': True,
 'age': 24.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 7.4958,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a48f'),
 'adult_male': True,
 'age': 47.0,
 'alive': 'no',
 'alone': True,
 'class': 'First',
 'deck': 'D',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 34.0208,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a490'),
 'adult_male': False,
 'age': 34.0,
 'alive': 'yes',
 'alone': True,
 'class': 'Second',
 'deck': 'F',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 10.5,
 'parch': 0,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a491'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 24.15,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a492'),
 'adult_male': False,
 'age': 36.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.0,
 'parch': 0,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a493'),
 'adult_male': True,
 'age': 32.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 7.8958,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a494'),
 'adult_male': False,
 'age': 30.0,
 'alive': 'yes',
 'alone': True,
 'class': 'First',
 'deck': 'B',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 93.5,
 'parch': 0,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a495'),
 'adult_male': True,
 'age': 22.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 7.8958,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a496'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 7.225,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a497'),
 'adult_male': False,
 'age': 44.0,
 'alive': 'yes',
 'alone': False,
 'class': 'First',
 'deck': 'B',
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 57.9792,
 'parch': 1,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a498'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 7.2292,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a499'),
 'adult_male': True,
 'age': 40.5,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 7.75,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a49a'),
 'adult_male': False,
 'age': 50.0,
 'alive': 'yes',
 'alone': True,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 10.5,
 'parch': 0,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a49b'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'First',
 'deck': 'C',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 221.7792,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a49c'),
 'adult_male': True,
 'age': 39.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 7.925,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a49d'),
 'adult_male': True,
 'age': 23.0,
 'alive': 'no',
 'alone': False,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 11.5,
 'parch': 1,
 'pclass': 2,
 'sex': 'male',
 'sibsp': 2,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a49e'),
 'adult_male': False,
 'age': 2.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.0,
 'parch': 1,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a49f'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 7.2292,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4a0'),
 'adult_male': True,
 'age': 17.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 7.2292,
 'parch': 1,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 1,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4a1'),
 'adult_male': False,
 'age': nan,
 'alive': 'yes',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 22.3583,
 'parch': 2,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4a2'),
 'adult_male': False,
 'age': 30.0,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 8.6625,
 'parch': 0,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 0,
 'survived': 0,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4a3'),
 'adult_male': False,
 'age': 7.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.25,
 'parch': 2,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4a4'),
 'adult_male': True,
 'age': 45.0,
 'alive': 'no',
 'alone': True,
 'class': 'First',
 'deck': 'B',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.55,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4a5'),
 'adult_male': False,
 'age': 30.0,
 'alive': 'yes',
 'alone': True,
 'class': 'First',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 106.425,
 'parch': 0,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4a6'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 14.5,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4a7'),
 'adult_male': False,
 'age': 22.0,
 'alive': 'yes',
 'alone': False,
 'class': 'First',
 'deck': 'B',
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 49.5,
 'parch': 2,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4a8'),
 'adult_male': False,
 'age': 36.0,
 'alive': 'yes',
 'alone': False,
 'class': 'First',
 'deck': 'B',
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 71.0,
 'parch': 2,
 'pclass': 1,
 'sex': 'female',
 'sibsp': 0,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4a9'),
 'adult_male': False,
 'age': 9.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 31.275,
 'parch': 2,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 4,
 'survived': 0,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4aa'),
 'adult_male': False,
 'age': 11.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 31.275,
 'parch': 2,
 'pclass': 3,
 'sex': 'female',
 'sibsp': 4,
 'survived': 0,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4ab'),
 'adult_male': True,
 'age': 32.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.0,
 'parch': 0,
 'pclass': 2,
 'sex': 'male',
 'sibsp': 1,
 'survived': 1,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4ac'),
 'adult_male': True,
 'age': 50.0,
 'alive': 'no',
 'alone': False,
 'class': 'First',
 'deck': 'C',
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 106.425,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 1,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4ad'),
 'adult_male': True,
 'age': 64.0,
 'alive': 'no',
 'alone': True,
 'class': 'First',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.0,
 'parch': 0,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4ae'),
 'adult_male': False,
 'age': 19.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.0,
 'parch': 0,
 'pclass': 2,
 'sex': 'female',
 'sibsp': 1,
 'survived': 1,
 'who': 'woman'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4af'),
 'adult_male': True,
 'age': nan,
 'alive': 'yes',
 'alone': True,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 13.8625,
 'parch': 0,
 'pclass': 2,
 'sex': 'male',
 'sibsp': 0,
 'survived': 1,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4b0'),
 'adult_male': True,
 'age': 33.0,
 'alive': 'no',
 'alone': False,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 20.525,
 'parch': 1,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 1,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4b1'),
 'adult_male': False,
 'age': 8.0,
 'alive': 'yes',
 'alone': False,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 36.75,
 'parch': 1,
 'pclass': 2,
 'sex': 'male',
 'sibsp': 1,
 'survived': 1,
 'who': 'child'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4b2'),
 'adult_male': True,
 'age': 17.0,
 'alive': 'yes',
 'alone': False,
 'class': 'First',
 'deck': 'C',
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 110.8833,
 'parch': 2,
 'pclass': 1,
 'sex': 'male',
 'sibsp': 0,
 'survived': 1,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4b3'),
 'adult_male': True,
 'age': 27.0,
 'alive': 'no',
 'alone': True,
 'class': 'Second',
 'deck': nan,
 'embark_town': 'Southampton',
 'embarked': 'S',
 'fare': 26.0,
 'parch': 0,
 'pclass': 2,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4b4'),
 'adult_male': True,
 'age': nan,
 'alive': 'no',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Queenstown',
 'embarked': 'Q',
 'fare': 7.8292,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,
 'survived': 0,
 'who': 'man'}
{'_id': ObjectId('63e7ada1fe31db2740c6a4b5'),
 'adult_male': True,
 'age': 22.0,
 'alive': 'yes',
 'alone': True,
 'class': 'Third',
 'deck': nan,
 'embark_town': 'Cherbourg',
 'embarked': 'C',
 'fare': 7.225,
 'parch': 0,
 'pclass': 3,
 'sex': 'male',
 'sibsp': 0,